# Build settings
permalink: /blog/:year/:month/:day/:title/
paginate: 5
paginate_path: "blog/:num/"
exclude: ["README.md"]
highlighter: rouge
markdown: kramdown

# Google Analytics
google__analytics:
  tracking-id: UA-102073967-1


# Site settings
title: "F&aacute;bio Schmidt"
description: "Computer Science Student, Python Developer and  Aspiring Data Scientist."

safe: false
url: https://fcschmidt.github.io/site/
url: https://fcschmidt.me
domain: fcschmidt.me
enforce_ssl: fcschmidt.me
twitter_user: fcschimidt
styles: main.css

# Social networks
social:
  twitter: "https://twitter.com/fcschimidt"
  instagram: "https://instagram.com/fcschmidt"
  linkedin: "https://www.linkedin.com/in/fcschmidt"
  github: "https://github.com/fcschmidt"
  contact: "mail:fcschimidt@gmail.com"
