# Build settings
permalink: /blog/:year/:month/:day/:title/
paginate: 5
paginate_path: "blog/:num/"
exclude: ["README.md"]
highlighter: rouge
markdown: kramdown

# Google Analytics
google__analytics:
  tracking-id: UA-85981803-1

# Disqus comments
disqus__shortname:
  user-name: fcschmidt

collections:
  docs:
    output: true


# Site settings
name: "F&aacute;bio Schmidt"
title: "F&aacute;bio Schmidt"
description: "Computer Science student, Autodidata, Python, R, AI interested"

safe: false
url: https://fcschmidt.github.io
url: https://fcschmidt.com
domain: fcschmidt.com
enforce_ssl: fcschmidt.com
twitter_user: fcschimidt
icon: favicon.ico
styles: main.css


# Author
author:
  name: "F&aacute;bio Schmidt"
  avatar: "avatar.png"
  bio: "Computer Science Student and Aspiring Data Scientist"
  location: Brazil
  email: fcschimidt@gmail.com
  twitter: fcschimidt
  gplus: +fábiocschmidt
  instagram:
  linkedin: fcschimidt
  github: fcschmidt
  gist: https://gist.github.com/fcschmidt
  bitbucket: fcschmidt
  stackoverflow: fcschmidt
  stackoverflow_story: fcschmidt


gems:
  # - jekyll-feed
  # - jekyll-admin
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore



