# Build settings
permalink: /blog/:year/:month/:day/:title/
paginate: 5
paginate_path: "blog/:num/"
exclude: ["README.md"]
highlighter: rouge
markdown: kramdown

# Google Analytics
google__analytics:
  tracking-id: UA-102073967-1

# Disqus comments
disqus__shortname:
  user-name: fcschmidt

collections:
  docs:
    output: true


# Site settings
name: "@fcschmidt"
title: "F&aacute;bio Schmidt"
description: "Computer Science Student, Front-end Developer and  Aspiring Data Scientist."

safe: false
url: https://fcschmidt.github.io
url: https://fcschmidt.me
domain: fcschmidt.me
enforce_ssl: fcschmidt.me
twitter_user: fcschimidt
icon: "favicon.png"
image: "mini-avatar.jpg"
styles: main.css


# Author
author:
  name: "F&aacute;bio Schmidt"
  avatar: "fb.jpg"
  bio: "Computer Science Student, Front-end Developer and  Aspiring Data Scientist."
  location: "Brazil"
  email: "fcschimidt [at] gmail [dot] com"
  email1: "contact [at] fcschmidt [dot] me"
  twitter: "fcschimidt"
#  gplus: +fábiocschmidt
  instagram:
  linkedin: "fcschmidt"
  github: "fcschmidt"
  bitbucket: "fcschmidt"
  stackoverflow: "fcschmidt"
  stackoverflow_story: "fcschmidt"
  medium: "fcschmidt"

links:
  twitter: "https://twitter.com/"
  gplus: "https://plus.google.com/u/0/"
  instagram: "https://instagram.com/"
  linkedin: "https://www.linkedin.com/in/"
  github: "https://github.com/"
  bitbucket: "https://bitbucket.org/"
  stack: "http://stackoverflow.com/story/"
  stackoverflow_story:
  lattes_url: "http://lattes.cnpq.br/3591699750918062"
  pt_resume: "https://github.com/fcschmidt/resume/blob/master/pt/resume_cv.pdf"
  en_resume: "https://github.com/fcschmidt/resume/blob/master/en/resume_cv.pdf"
  python: "https://www.python.org/"
  r: "https://www.r-project.org/"
  mit: "http://opensource.org/licenses/MIT"

gems:
  # - jekyll-feed
  # - jekyll-admin
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore



