# Build settings
penalink: /:year/:month/:day/:title/
paginate: 5
paginate_path: "blog/:num/"
exclude: ["README.md"]
highlighter: rouge
markdown: kramdown

safe: false
baseurl: ""

# Site settings
name: "F&aacute;bio Schmidt"
title: "F&aacute;bio Schmidt"
description: "Computer Science student, Autodidata, Lifehacker, Python, R enthusiast and AI interested"
twitter_user: fcschimidt
image: #
icon: favicon.ico
styles: main.min.css

url: https://fcschmidt.com
enforce_ssl: fcschmidt.com
domain: fcschmidt.com

# Google Analytics
google__analytics:
  tracking-id: UA-85981803-1


# Menu
nav:
  - name: home
    url: /
  - name: about
    url: /about/
  - name: blog
    url: /blog/
  - name: projects
    url: /projects/
  - name: research
    url: /research/
